branches:
  only:
  - master
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.107.0/hugo_0.107.0_linux-amd64.deb
  - sudo dpkg -i hugo_0.107.0_linux-amd64.deb
  - rm -rf public || exit 0
script:
  - hugo
  - echo 'saturnism.me' > public/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
